### ISSUE TITLE
TWiT Live Stream

### ISSUE THREAD

**Issue by notanewbie** [notanewbie/LegalStream#1]
Hi! I noticed TWiT stopped hosting their stream on their site. Does anyone know where I can find a reliable IPTV stream of TWiT Live?

**Comment by JeremyPlease** [comment]
Here it is:
http://iphone-streaming.ustream.tv/uhls/1524/streams/live/iphone/playlist.m3u8

Source: http://wiki.twit.tv/wiki/TWiT_Live#Advanced_Methods_for_Streaming_TWiT_Live_Video

**Comment by notanewbie** [comment]
Thanks!
