### ISSUE TITLE
More Packages?

### ISSUE THREAD

**Issue by notanewbie** [notanewbie/LegalStream#10]
Here's a topic where users can request new packages.

The reason I bring this up is because I am curious; do you guys want further fragmentation of the stream packages? That way users will be able to create their own playlists including only liberal news channels, local channels (by state/province), etc.

**Comment by Kenner-G** [comment]
Colorado >>> NBC / CNN / Univision (Latino) / etc.

**Comment by notanewbie** [comment]
Sorry; I'm not sure what you mean.

**Comment by Kenner-G** [comment]
United States (Colorado):

NBC
CBS
ABC
Univision
Telemundo

**Comment by notanewbie** [comment]
Ah, I see. Yes, I do plan to split organize locals by state when I get the chance; also, I'm trying to only include English-speaking stations.

P.S. I was like "CNN isn't a Colorado station!"

**Comment by markosjal** [comment]
Yes I think fragmentation is great.

I have put together my playlist but it was all copying and pastng while would be far better to link
