### ISSUE TITLE
Want to join Forces

### ISSUE THREAD

**Issue by tdbnz123** [notanewbie/LegalStream#11]
Hi there

I was wondering if you are keen on joining forces and having your content on a kodi addon I am a developer for the kodi media center 

reach me on Twitter @teamxkodi

**Comment by notanewbie** [comment]
Yeah, I really wanted to add Kodi support but wasn't sure how. What do I have to do?

**Comment by Kenner-G** [comment]
@notanewbie remember me? FYI, tbdnz123 DOES not work for Kodi, he is working for a company that intends to gain money from your links.
