### ISSUE TITLE
Olympic Channels are down?

### ISSUE THREAD

**Issue by Kenner-G** [notanewbie/LegalStream#13]
Hey,

All of the Olympic Channels are down. Are they not 24/7 or?

**Comment by Kenner-G** [comment]
**UPDATE**

I just extracted the latest Olympic Channel URL:

http://sprtlive7.akamaized.net/hls/live/586269/nbc-olympics0219054452/exp=1519140621~acl=%2fhls%2flive%2f586269*~data=hdntl~hmac=aa7161427a4e5b3fbeefc65cf42553166fb4389c29fd0f944e437db9113aa375/OTT07_VIDEO_1_4064000.m3u8

**I think the links are updated daily.**

**Comment by notanewbie** [comment]
Nope, they're still up. Channels 2-5 seem to be overflow streams. Also, I'm pretty sure the link you just provided is from the NBC Olympic Channel, not IOC's Olympic Channel. Also, it's dead ATM...

**Comment by Kenner-G** [comment]
Hm,

Probably means that it's illegal removing alleged links.

**Comment by notanewbie** [comment]
Thanks!
