### ISSUE TITLE
NASA

### ISSUE THREAD

**Issue by skydrome** [notanewbie/LegalStream#17]
Nasa's direct streams now require that the Referer http field is set to www.nasa.gov
For media players that cant send custom headers, links to the ustream feeds are

NASA TV
http://iphone-streaming.ustream.tv/uhls/6540154/streams/live/iphone/playlist.m3u8
NASA TV Media Channel
http://iphone-streaming.ustream.tv/uhls/10414700/streams/live/iphone/playlist.m3u8

**Comment by notanewbie** [comment]
Thanks!
