### ISSUE TITLE
FastoTV common channels

### ISSUE THREAD

**Issue by topilski** [notanewbie/LegalStream#18]
Hi, i'am developer of [FastoTV ](https://github.com/fastogt/fastotv)(opensource iptv solution), the main goal in FastoTV project was give ability user to select which channels he want to see in player. So in profile page user have offical channels and own private which visible only for him. I want ask you, if your channels is legal can we add it into offical channels group which will be visible for all users?

**Comment by notanewbie** [comment]
Yeah, your service seems pretty cool! I'd love to have you add channels from my service! The only channel that I'm not sure is (but is probably) legal is Steven Universe 24/7.

Just curious, do you plan on offering support for Roku, Fire TV, Apple TV, Android iOS or web?

**Comment by topilski** [comment]
Hi @notanewbie , thank you for your reply, if i give you permissions to datatabase will u be  able to add channels? You will be administrator of offical channels, what do you think about it? It is opensource we can do whatever we want. If users need android or other features, it will be done. Now i'm looking for feedback of the  project and some proposals or partners.

**Comment by topilski** [comment]
Hi @notanewbie i sent you some email, please check your inbox.

**Comment by Kenner-G** [comment]
Seems like someone wants to get a free services.

**Comment by notanewbie** [comment]
@Kenner-G I don't mind.

I'm not in this for the money, heh heh...
