### ISSUE TITLE
CCTV-13 Unavailable

### ISSUE THREAD

**Issue by lewisje** [notanewbie/LegalStream#2]
When I tried to use this list, I found that the CCTV-13 stream gave me this static image for 20 seconds before ending:

![cctv-13](https://user-images.githubusercontent.com/4865237/29497748-b6210486-85bb-11e7-8d45-e2e0b6f519a9.png)

Copyfish interpreted the text as

> 您所访问的播放地址已失效，
请及时更新您的播放器版本。

and it translates (from Chinese Simplified) to

> You can access the playback address has expired, Please update your Player version.

It seems like CCTV has mostly re-branded for the outside world to CGTN, and it could be that CCTV-13 is no longer available outside China.

**Comment by lewisje** [comment]
FTR, CGTN America still works, and it's different from CGTN English, so you didn't need to remove it: https://github.com/notanewbie/LegalStream/commit/70f40470191c239f95d4edad1b8a1fdedead174f

**Comment by notanewbie** [comment]
Okay, I added it. Thanks for letting me know!
