### ISSUE TITLE
PAC-12 streams , One missing

### ISSUE THREAD

**Issue by markosjal** [notanewbie/LegalStream#21]
I found the PAC-12 streams here band love them , but it see,s PAC-12 Bay Area is missing. JUst FYI but great if you locate it!

**Comment by notanewbie** [comment]
I don't think I have the PAC-12 streams here..which package are you referring to? Also, I can't get the m3u8s legitimately. However, you can watch the PAC-12 Network legally (and for free!) here: https://www.youtube.com/user/pac12networksintl/live

**Comment by markosjal** [comment]
oops maybe they are not from here but appear to be legit . Not sure where I got them from in that case.
