### ISSUE TITLE
Newsmax TV link is outdated

### ISSUE THREAD

**Issue by hihiyan** [notanewbie/LegalStream#6]
The current official one: 
http://hlsdpi-cdn-as2.totalstream.net/dpilive/vidilliontv/vtv/pursuitlive/playlist.m3u8

**Comment by hihiyan** [comment]
Sorry, it is: https://nmxlive.akamaized.net/hls/live/529965/Live_1/index.m3u8
the above Pursuit TV.

**Comment by notanewbie** [comment]
Thanks for the update. I actually did not know about Pursuit TV, thanks for sending the URL.
